# Generated by Django 2.2.1 on 2019-06-03 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=100)),
                ('ap_pat', models.CharField(max_length=100)),
                ('ap_mat', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=50)),
                ('aniosExperiencia', models.IntegerField()),
                ('fechaNacimiento', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Profesor',
            },
        ),
    ]
